// Code generated by 'yaegi extract github.com/rohanthewiz/bytdb'. DO NOT EDIT.

package symbols

import (
	"github.com/rohanthewiz/bytdb"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/rohanthewiz/bytdb/bytdb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"CanonJSONB":           reflect.ValueOf(bytdb.CanonJSONB),
		"CanonTextArray":       reflect.ValueOf(bytdb.CanonTextArray),
		"ErrText":              reflect.ValueOf(bytdb.ErrText),
		"ErrTxConflict":        reflect.ValueOf(&bytdb.ErrTxConflict).Elem(),
		"FKCascade":            reflect.ValueOf(constant.MakeFromLiteral("\"cascade\"", token.STRING, 0)),
		"FormatDate":           reflect.ValueOf(bytdb.FormatDate),
		"FormatTextArray":      reflect.ValueOf(bytdb.FormatTextArray),
		"FormatTimestamp":      reflect.ValueOf(bytdb.FormatTimestamp),
		"FormatUUID":           reflect.ValueOf(bytdb.FormatUUID),
		"Open":                 reflect.ValueOf(bytdb.Open),
		"ParseDate":            reflect.ValueOf(bytdb.ParseDate),
		"ParseTextArray":       reflect.ValueOf(bytdb.ParseTextArray),
		"ParseTimestamp":       reflect.ValueOf(bytdb.ParseTimestamp),
		"ParseUUID":            reflect.ValueOf(bytdb.ParseUUID),
		"TBool":                reflect.ValueOf(bytdb.TBool),
		"TBytes":               reflect.ValueOf(bytdb.TBytes),
		"TDate":                reflect.ValueOf(bytdb.TDate),
		"TFloat":               reflect.ValueOf(bytdb.TFloat),
		"TInt":                 reflect.ValueOf(bytdb.TInt),
		"TJSONB":               reflect.ValueOf(bytdb.TJSONB),
		"TString":              reflect.ValueOf(bytdb.TString),
		"TTextArray":           reflect.ValueOf(bytdb.TTextArray),
		"TTimestamp":           reflect.ValueOf(bytdb.TTimestamp),
		"TUUID":                reflect.ValueOf(bytdb.TUUID),
		"WithConcurrentWrites": reflect.ValueOf(bytdb.WithConcurrentWrites),
		"WithEncryptionKey":    reflect.ValueOf(bytdb.WithEncryptionKey),
		"WithSyncNever":        reflect.ValueOf(bytdb.WithSyncNever),

		// type definitions
		"CheckDesc": reflect.ValueOf((*bytdb.CheckDesc)(nil)),
		"ColType":   reflect.ValueOf((*bytdb.ColType)(nil)),
		"Column":    reflect.ValueOf((*bytdb.Column)(nil)),
		"Engine":    reflect.ValueOf((*bytdb.Engine)(nil)),
		"FKDesc":    reflect.ValueOf((*bytdb.FKDesc)(nil)),
		"FKRef":     reflect.ValueOf((*bytdb.FKRef)(nil)),
		"IndexCol":  reflect.ValueOf((*bytdb.IndexCol)(nil)),
		"IndexDesc": reflect.ValueOf((*bytdb.IndexDesc)(nil)),
		"Row":       reflect.ValueOf((*bytdb.Row)(nil)),
		"Savepoint": reflect.ValueOf((*bytdb.Savepoint)(nil)),
		"SeqDesc":   reflect.ValueOf((*bytdb.SeqDesc)(nil)),
		"TableDesc": reflect.ValueOf((*bytdb.TableDesc)(nil)),
		"Txn":       reflect.ValueOf((*bytdb.Txn)(nil)),
		"ViewDesc":  reflect.ValueOf((*bytdb.ViewDesc)(nil)),
	}
}
