// Code generated by 'yaegi extract github.com/rohanthewiz/bytdb/tuple'. DO NOT EDIT.

package symbols

import (
	"github.com/rohanthewiz/bytdb/tuple"
	"reflect"
)

func init() {
	Symbols["github.com/rohanthewiz/bytdb/tuple/tuple"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Append":     reflect.ValueOf(tuple.Append),
		"AppendDesc": reflect.ValueOf(tuple.AppendDesc),
		"Compare":    reflect.ValueOf(tuple.Compare),
		"Decode":     reflect.ValueOf(tuple.Decode),
		"DecodeOne":  reflect.ValueOf(tuple.DecodeOne),
		"Encode":     reflect.ValueOf(tuple.Encode),
		"PrefixEnd":  reflect.ValueOf(tuple.PrefixEnd),
	}
}
