// Code generated by 'yaegi extract github.com/rohanthewiz/bytdb/sql'. DO NOT EDIT.

package symbols

import (
	"github.com/rohanthewiz/bytdb/sql"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/rohanthewiz/bytdb/sql/sql"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AggAvg":                  reflect.ValueOf(sql.AggAvg),
		"AggCount":                reflect.ValueOf(sql.AggCount),
		"AggMax":                  reflect.ValueOf(sql.AggMax),
		"AggMin":                  reflect.ValueOf(sql.AggMin),
		"AggNone":                 reflect.ValueOf(sql.AggNone),
		"AggSum":                  reflect.ValueOf(sql.AggSum),
		"BoundCurrentRow":         reflect.ValueOf(sql.BoundCurrentRow),
		"BoundOffsetFollowing":    reflect.ValueOf(sql.BoundOffsetFollowing),
		"BoundOffsetPreceding":    reflect.ValueOf(sql.BoundOffsetPreceding),
		"BoundUnboundedFollowing": reflect.ValueOf(sql.BoundUnboundedFollowing),
		"BoundUnboundedPreceding": reflect.ValueOf(sql.BoundUnboundedPreceding),
		"ExcludeCurrentRow":       reflect.ValueOf(sql.ExcludeCurrentRow),
		"ExcludeGroup":            reflect.ValueOf(sql.ExcludeGroup),
		"ExcludeNoOthers":         reflect.ValueOf(sql.ExcludeNoOthers),
		"ExcludeTies":             reflect.ValueOf(sql.ExcludeTies),
		"FrameGroups":             reflect.ValueOf(sql.FrameGroups),
		"FrameRange":              reflect.ValueOf(sql.FrameRange),
		"FrameRows":               reflect.ValueOf(sql.FrameRows),
		"JoinCross":               reflect.ValueOf(sql.JoinCross),
		"JoinInner":               reflect.ValueOf(sql.JoinInner),
		"JoinLeft":                reflect.ValueOf(sql.JoinLeft),
		"New":                     reflect.ValueOf(sql.New),
		"OpEQ":                    reflect.ValueOf(sql.OpEQ),
		"OpGE":                    reflect.ValueOf(sql.OpGE),
		"OpGT":                    reflect.ValueOf(sql.OpGT),
		"OpIsNotNull":             reflect.ValueOf(sql.OpIsNotNull),
		"OpIsNull":                reflect.ValueOf(sql.OpIsNull),
		"OpLE":                    reflect.ValueOf(sql.OpLE),
		"OpLT":                    reflect.ValueOf(sql.OpLT),
		"OpNE":                    reflect.ValueOf(sql.OpNE),
		"OpNotRegex":              reflect.ValueOf(sql.OpNotRegex),
		"OpNotRegexI":             reflect.ValueOf(sql.OpNotRegexI),
		"OpRegex":                 reflect.ValueOf(sql.OpRegex),
		"OpRegexI":                reflect.ValueOf(sql.OpRegexI),
		"Parse":                   reflect.ValueOf(sql.Parse),
		"ServerVersion":           reflect.ValueOf(constant.MakeFromLiteral("\"16.0 (bytdb)\"", token.STRING, 0)),
		"TxActive":                reflect.ValueOf(sql.TxActive),
		"TxFailed":                reflect.ValueOf(sql.TxFailed),
		"TxIdle":                  reflect.ValueOf(sql.TxIdle),
		"TxnBegin":                reflect.ValueOf(sql.TxnBegin),
		"TxnCommit":               reflect.ValueOf(sql.TxnCommit),
		"TxnRelease":              reflect.ValueOf(sql.TxnRelease),
		"TxnRollback":             reflect.ValueOf(sql.TxnRollback),
		"TxnRollbackTo":           reflect.ValueOf(sql.TxnRollbackTo),
		"TxnSavepoint":            reflect.ValueOf(sql.TxnSavepoint),
		"WinDenseRank":            reflect.ValueOf(sql.WinDenseRank),
		"WinFirstValue":           reflect.ValueOf(sql.WinFirstValue),
		"WinLag":                  reflect.ValueOf(sql.WinLag),
		"WinLastValue":            reflect.ValueOf(sql.WinLastValue),
		"WinLead":                 reflect.ValueOf(sql.WinLead),
		"WinNone":                 reflect.ValueOf(sql.WinNone),
		"WinNthValue":             reflect.ValueOf(sql.WinNthValue),
		"WinRank":                 reflect.ValueOf(sql.WinRank),
		"WinRowNumber":            reflect.ValueOf(sql.WinRowNumber),

		// type definitions
		"Activity":       reflect.ValueOf((*sql.Activity)(nil)),
		"AddColumn":      reflect.ValueOf((*sql.AddColumn)(nil)),
		"AddConstraint":  reflect.ValueOf((*sql.AddConstraint)(nil)),
		"AddFK":          reflect.ValueOf((*sql.AddFK)(nil)),
		"AggFunc":        reflect.ValueOf((*sql.AggFunc)(nil)),
		"AlterSequence":  reflect.ValueOf((*sql.AlterSequence)(nil)),
		"And":            reflect.ValueOf((*sql.And)(nil)),
		"BoolExpr":       reflect.ValueOf((*sql.BoolExpr)(nil)),
		"CTE":            reflect.ValueOf((*sql.CTE)(nil)),
		"CheckDef":       reflect.ValueOf((*sql.CheckDef)(nil)),
		"ColDef":         reflect.ValueOf((*sql.ColDef)(nil)),
		"ColRef":         reflect.ValueOf((*sql.ColRef)(nil)),
		"Cond":           reflect.ValueOf((*sql.Cond)(nil)),
		"CreateIndex":    reflect.ValueOf((*sql.CreateIndex)(nil)),
		"CreateSequence": reflect.ValueOf((*sql.CreateSequence)(nil)),
		"CreateTable":    reflect.ValueOf((*sql.CreateTable)(nil)),
		"CreateView":     reflect.ValueOf((*sql.CreateView)(nil)),
		"DB":             reflect.ValueOf((*sql.DB)(nil)),
		"Delete":         reflect.ValueOf((*sql.Delete)(nil)),
		"DropColumn":     reflect.ValueOf((*sql.DropColumn)(nil)),
		"DropConstraint": reflect.ValueOf((*sql.DropConstraint)(nil)),
		"DropIndex":      reflect.ValueOf((*sql.DropIndex)(nil)),
		"DropSequence":   reflect.ValueOf((*sql.DropSequence)(nil)),
		"DropTable":      reflect.ValueOf((*sql.DropTable)(nil)),
		"DropView":       reflect.ValueOf((*sql.DropView)(nil)),
		"ExAgg":          reflect.ValueOf((*sql.ExAgg)(nil)),
		"ExAnd":          reflect.ValueOf((*sql.ExAnd)(nil)),
		"ExAny":          reflect.ValueOf((*sql.ExAny)(nil)),
		"ExArith":        reflect.ValueOf((*sql.ExArith)(nil)),
		"ExArray":        reflect.ValueOf((*sql.ExArray)(nil)),
		"ExCase":         reflect.ValueOf((*sql.ExCase)(nil)),
		"ExCast":         reflect.ValueOf((*sql.ExCast)(nil)),
		"ExCmp":          reflect.ValueOf((*sql.ExCmp)(nil)),
		"ExCol":          reflect.ValueOf((*sql.ExCol)(nil)),
		"ExFunc":         reflect.ValueOf((*sql.ExFunc)(nil)),
		"ExIn":           reflect.ValueOf((*sql.ExIn)(nil)),
		"ExIndex":        reflect.ValueOf((*sql.ExIndex)(nil)),
		"ExIsNull":       reflect.ValueOf((*sql.ExIsNull)(nil)),
		"ExLit":          reflect.ValueOf((*sql.ExLit)(nil)),
		"ExNot":          reflect.ValueOf((*sql.ExNot)(nil)),
		"ExOr":           reflect.ValueOf((*sql.ExOr)(nil)),
		"ExSub":          reflect.ValueOf((*sql.ExSub)(nil)),
		"ExWhen":         reflect.ValueOf((*sql.ExWhen)(nil)),
		"ExWindow":       reflect.ValueOf((*sql.ExWindow)(nil)),
		"Explain":        reflect.ValueOf((*sql.Explain)(nil)),
		"Expr":           reflect.ValueOf((*sql.Expr)(nil)),
		"FKDef":          reflect.ValueOf((*sql.FKDef)(nil)),
		"FrameBound":     reflect.ValueOf((*sql.FrameBound)(nil)),
		"FrameBoundType": reflect.ValueOf((*sql.FrameBoundType)(nil)),
		"FrameExclusion": reflect.ValueOf((*sql.FrameExclusion)(nil)),
		"FrameMode":      reflect.ValueOf((*sql.FrameMode)(nil)),
		"FromItem":       reflect.ValueOf((*sql.FromItem)(nil)),
		"GroupItem":      reflect.ValueOf((*sql.GroupItem)(nil)),
		"Insert":         reflect.ValueOf((*sql.Insert)(nil)),
		"JoinType":       reflect.ValueOf((*sql.JoinType)(nil)),
		"Not":            reflect.ValueOf((*sql.Not)(nil)),
		"OnConflict":     reflect.ValueOf((*sql.OnConflict)(nil)),
		"Or":             reflect.ValueOf((*sql.Or)(nil)),
		"OrderItem":      reflect.ValueOf((*sql.OrderItem)(nil)),
		"Param":          reflect.ValueOf((*sql.Param)(nil)),
		"Pred":           reflect.ValueOf((*sql.Pred)(nil)),
		"PredOp":         reflect.ValueOf((*sql.PredOp)(nil)),
		"RenameColumn":   reflect.ValueOf((*sql.RenameColumn)(nil)),
		"RenameTable":    reflect.ValueOf((*sql.RenameTable)(nil)),
		"Result":         reflect.ValueOf((*sql.Result)(nil)),
		"Returning":      reflect.ValueOf((*sql.Returning)(nil)),
		"Select":         reflect.ValueOf((*sql.Select)(nil)),
		"SelectItem":     reflect.ValueOf((*sql.SelectItem)(nil)),
		"SeqOptions":     reflect.ValueOf((*sql.SeqOptions)(nil)),
		"Session":        reflect.ValueOf((*sql.Session)(nil)),
		"SetVar":         reflect.ValueOf((*sql.SetVar)(nil)),
		"ShowVar":        reflect.ValueOf((*sql.ShowVar)(nil)),
		"Statement":      reflect.ValueOf((*sql.Statement)(nil)),
		"Stmt":           reflect.ValueOf((*sql.Stmt)(nil)),
		"StmtInfo":       reflect.ValueOf((*sql.StmtInfo)(nil)),
		"Truncate":       reflect.ValueOf((*sql.Truncate)(nil)),
		"TxStatus":       reflect.ValueOf((*sql.TxStatus)(nil)),
		"TxnControl":     reflect.ValueOf((*sql.TxnControl)(nil)),
		"TxnKind":        reflect.ValueOf((*sql.TxnKind)(nil)),
		"UnionArm":       reflect.ValueOf((*sql.UnionArm)(nil)),
		"Update":         reflect.ValueOf((*sql.Update)(nil)),
		"WinFunc":        reflect.ValueOf((*sql.WinFunc)(nil)),
		"WindowFrame":    reflect.ValueOf((*sql.WindowFrame)(nil)),

		// interface wrapper definitions
		"_BoolExpr":  reflect.ValueOf((*_github_com_rohanthewiz_bytdb_sql_BoolExpr)(nil)),
		"_Expr":      reflect.ValueOf((*_github_com_rohanthewiz_bytdb_sql_Expr)(nil)),
		"_Statement": reflect.ValueOf((*_github_com_rohanthewiz_bytdb_sql_Statement)(nil)),
	}
}

// _github_com_rohanthewiz_bytdb_sql_BoolExpr is an interface wrapper for BoolExpr type
type _github_com_rohanthewiz_bytdb_sql_BoolExpr struct {
	IValue interface{}
}

// _github_com_rohanthewiz_bytdb_sql_Expr is an interface wrapper for Expr type
type _github_com_rohanthewiz_bytdb_sql_Expr struct {
	IValue interface{}
}

// _github_com_rohanthewiz_bytdb_sql_Statement is an interface wrapper for Statement type
type _github_com_rohanthewiz_bytdb_sql_Statement struct {
	IValue interface{}
}
