// Code generated by 'yaegi extract github.com/rohanthewiz/go-styl'. DO NOT EDIT.

package symbols

import (
	"github.com/rohanthewiz/go-styl"
	"reflect"
)

func init() {
	Symbols["github.com/rohanthewiz/go-styl/styl"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Build":          reflect.ValueOf(styl.Build),
		"BuildFile":      reflect.ValueOf(styl.BuildFile),
		"Compile":        reflect.ValueOf(styl.Compile),
		"CompileFile":    reflect.ValueOf(styl.CompileFile),
		"CompileFileMap": reflect.ValueOf(styl.CompileFileMap),
		"CompileMap":     reflect.ValueOf(styl.CompileMap),
		"CompileReader":  reflect.ValueOf(styl.CompileReader),
		"Extract":        reflect.ValueOf(styl.Extract),
		"ExtractFile":    reflect.ValueOf(styl.ExtractFile),
		"Prune":          reflect.ValueOf(styl.Prune),
		"PruneFile":      reflect.ValueOf(styl.PruneFile),
		"UsedFromHTML":   reflect.ValueOf(styl.UsedFromHTML),

		// type definitions
		"Manifest": reflect.ValueOf((*styl.Manifest)(nil)),
		"Options":  reflect.ValueOf((*styl.Options)(nil)),
		"Result":   reflect.ValueOf((*styl.Result)(nil)),
		"Used":     reflect.ValueOf((*styl.Used)(nil)),
		"Var":      reflect.ValueOf((*styl.Var)(nil)),
	}
}
