// Hand-written PARTIAL extract of os — not generated by gen.sh, and that is
// deliberate. The Database track's harnesses open a bytdb file per run and
// need exactly two things: a stable temp location and a way to start fresh
// (and clean up, so native verify runs don't litter /tmp). Extracting the
// whole os package would also hand interpreted code os.Exit — which, in the
// browser, terminates the resident wasm module and bricks every subsequent
// run until the worker is respawned — plus a pile of process/env surface no
// lesson needs. A three-symbol table keeps the blast radius at zero.
//
// In the browser these calls hit the in-memory fs shim (engine/memfs.js);
// natively they hit the real filesystem. Same code, both worlds.
package symbols

import (
	"os"
	"reflect"
)

func init() {
	Symbols["os/os"] = map[string]reflect.Value{
		"Remove":    reflect.ValueOf(os.Remove),
		"RemoveAll": reflect.ValueOf(os.RemoveAll),
		"TempDir":   reflect.ValueOf(os.TempDir),
	}
}
